"""
WebScribe Data Models

SQLModel table definitions for Job, MarkdownNote, and Template entities.
"""

from datetime import datetime, timezone
from enum import Enum
from uuid import uuid4
from typing import Optional

from sqlmodel import Field, SQLModel


class JobStatus(str, Enum):
    """Job processing status"""
    queued = "queued"
    running = "running"
    done = "done"
    failed = "failed"


class Job(SQLModel, table=True):
    """
    Represents a scraping and processing job for a single URL.

    A Job tracks the full lifecycle of processing one URL, from initial
    submission through scraping, de-noising, and AI synthesis.
    """
    __tablename__ = "job"

    id: str = Field(
        default_factory=lambda: str(uuid4()),
        primary_key=True,
        description="Unique job identifier"
    )
    url: str = Field(
        description="The URL to scrape and process"
    )
    engine: str = Field(
        description="Scraper engine: 'static' or 'dynamic'"
    )
    template_id: str = Field(
        description="ID of the template to use for AI synthesis"
    )
    status: JobStatus = Field(
        default=JobStatus.queued,
        description="Current job status"
    )
    logs: str = Field(
        default="[]",
        description="JSON-encoded list of log messages"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Job creation timestamp"
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last update timestamp"
    )


class MarkdownNote(SQLModel, table=True):
    """
    Represents a structured Markdown note generated by the AI engine.

    Multiple MarkdownNote records can be linked to a single Job, representing
    different AI synthesis runs with different templates.
    """
    __tablename__ = "markdownnote"

    id: str = Field(
        default_factory=lambda: str(uuid4()),
        primary_key=True,
        description="Unique note identifier"
    )
    job_id: str = Field(
        foreign_key="job.id",
        description="ID of the parent Job"
    )
    title: str = Field(
        description="Note title extracted by AI"
    )
    content: str = Field(
        description="Full Markdown body of the note"
    )
    template_id: str = Field(
        description="ID of the template used for synthesis"
    )
    tags: str = Field(
        default="[]",
        description="JSON-encoded list of tags"
    )
    version: int = Field(
        default=1,
        description="Version number for this job (increments with re-runs)"
    )
    saved_path: Optional[str] = Field(
        default=None,
        description="Absolute path if saved to Knowledge Base"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Note creation timestamp"
    )


class Template(SQLModel, table=True):
    """
    Represents an AI prompt template for synthesizing Markdown notes.

    Templates define how the raw scraped content should be structured
    and what information should be extracted.
    """
    __tablename__ = "template"

    id: str = Field(
        primary_key=True,
        description="Unique template identifier (slug format)"
    )
    name: str = Field(
        description="Display name for the template"
    )
    prompt_template: str = Field(
        description="Jinja2 template string for the LLM prompt"
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Template creation timestamp"
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Last update timestamp"
    )
